### ISSUE TITLE
could not resolve schema for service at path "package.version.ServiceName": proto: not found

### ISSUE THREAD

**Issue by rauanmayemir** [connectrpc/vanguard-go#137]
I can run my grpc server without transcoder and it will work, but following the example [here](https://github.com/connectrpc/vanguard-go/blob/6278ca9ae160688805cf6be2acad746fcc1f146e/internal/examples/connect-grpc/cmd/server/main.go#L42) crashes it with:
```
 could not resolve schema for service at path "package.version.ServiceName": proto: not found
 ```

Tried both `v0.3.0` and latest from `main`.

**Comment by jhump** [comment]
@rauanmayemir, are you using the normal protoc-gen-grpc-go plugin to generate the gRPC client and server stubs? If your service is providing any service that is dynamic (not registered from generated `Register` functions produced by the protoc-gen-grpc-go plugin), that will cause this issue.

This error could also happen if there is an issue with the embedded descriptors for your service. This could possibly happen if your proto files are using import paths that do not match the way the imported files actually get registered. You could read more about this issue here: https://buf.build/docs/reference/protobuf-files-and-packages#imports

**Comment by rauanmayemir** [comment]
@jhump thanks, import_path must be issue. I’ll try to sort it out and see if it fixes it.

P.S: I’m not using protoc-gen-grpc-go, but rather ‘proxying’ equests.

**Comment by rauanmayemir** [comment]
Turns out this is not a single blocker. I was parsing proto files with a different go library that didn't register definitions in protoregistry, so vanguard was failing to look up service definitions.

What would be a preferable to do that? I'm not running an actual proxy, but rather shelling out requests to a handler (i.e golang 'proxies' requests to a handler written in PHP).

At the same time, I do want vanguard to support all the reflection and json-transcoding stuff and generally know the types.

**Comment by rauanmayemir** [comment]
@jhump Thank you so much, I used your protoreflect library for parsing and was able to set up vanguard in front of my grpc server. 👍
